### ISSUE TITLE
plagarised company quote

### ISSUE THREAD

**Issue by sushant12** [bajratech/bajratech.github.io#19]
@akrmhrjn  @loomilahada  `Understanding Bajra's Technology, Perception and Culture.` is similar to YIPL`s quote on their weekly. This is not very creative. Can we think of something good?

**Comment by akrmhrjn** [comment]
@sushant12 let's discuss and change it.

**Comment by akrmhrjn** [comment]
@sushant12 _Understanding Bajra's Technology, Perception and Culture_ has been changed to **An Exposure to Bajra Family** as suggested by @loomilahada .

**Comment by sushantbajra** [comment]
That is really great
