### ISSUE TITLE
Getting started with Bajra weekly is outdated

### ISSUE THREAD

**Issue by sushant12** [bajratech/bajratech.github.io#20]
@akrmhrjn @degendra @SumanRajSharma  the readme.md and blog post on getting started with bajra weekly needs to be updated to match the latest process of posting a blog.

**Comment by akrmhrjn** [comment]
@sushantbajra I will look into this.

**Comment by akrmhrjn** [comment]
@sushant12 @degendra @SumanRajSharma @loomilahada The blog has been updated.

**Comment by sushantbajra** [comment]
Good to know
